name: build-linux

on:
  push:
  pull_request:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential    \
                           gcc-10                  \
                           g++-10                  \
                           pkg-config              \
                           cmake                   \
                           make                    \
                           libglfw3-dev            \
                           libglm-dev              \
                           libmagic-dev            \
                           libssl-dev              \
                           libcapstone-dev         \
                           llvm-dev                \
                           nlohmann-json3-dev      \
                           python3-dev             \

    - name: Build
      shell: bash
      run: |
        mkdir build
        cd build
        CC=gcc-10 CXX=g++-10 cmake ..
        make -j 4

    - uses: actions/upload-artifact@v2
      with:
        name: upload-binanry
        path: |
          cmake-build-release/
          build-linux/
